apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: localhost:5000/custom-nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: custom-nginx  
  ports: 
  - port: 80
    targetPort: 80